#!/bin/bash

echo "=== YAML/Describe 双模式切换功能测试 ==="
echo ""
echo "本测试验证在YAML和Describe模式下的双模式切换功能："
echo ""
echo "🎯 功能说明："
echo "1. 文本选择模式（默认）："
echo "   - 可以选中并复制文本内容"  
echo "   - 使用J/K键或方向键滚动"
echo "   - 状态栏显示：文本选择模式"
echo ""
echo "2. 鼠标滚轮模式："
echo "   - 可以使用鼠标滚轮快速滚动"
echo "   - 无法选择文本"
echo "   - 状态栏显示：鼠标滚轮模式"
echo ""
echo "🔄 模式切换："
echo "   - 按 M 键在两种模式间切换"
echo "   - 切换是即时生效的"
echo "   - 进入YAML/Describe模式时默认为文本选择模式"
echo ""
echo "📋 测试步骤："
echo "1. 启动应用，进入Pod列表"
echo "2. 选择一个Pod，按 Space 进入Describe模式"
echo "3. 默认应为「文本选择模式」，尝试选中复制文本"
echo "4. 按 M 键切换到「鼠标滚轮模式」，尝试用鼠标滚轮滚动"
echo "5. 再按 M 键切换回「文本选择模式」"
echo "6. 按 Y 键进入YAML模式，测试相同的切换功能"
echo "7. 验证在YAML模式下也能正常切换和复制内容"
echo ""
echo "✅ 预期结果："
echo "- 文本选择模式：可以拖拽选择并复制YAML/Describe内容"
echo "- 鼠标滚轮模式：鼠标滚轮可以快速滚动，但无法选择文本"
echo "- 状态栏和标题栏清楚显示当前模式"
echo "- M键切换即时生效，用户体验流畅"
echo ""

read -p "按Enter键开始测试..."

cd /Users/zhanglianwei/github/kube
cargo run

echo ""
echo "=== 测试完成 ==="
echo ""
echo "请报告测试结果："
echo "✓ 默认文本选择模式是否正常？"
echo "✓ M键切换是否即时生效？"
echo "✓ 鼠标滚轮模式滚动是否正常？"
echo "✓ 文本选择模式复制是否正常？"
echo "✓ YAML模式下功能是否正常？"
echo "✓ 状态栏提示是否清楚？"
echo ""
echo "这个双模式方案完美解决了您的需求："
echo "• 既能滚动又能复制文本"
echo "• 操作简单（只需按M键切换）" 
echo "• 默认优先文本选择，满足复制YAML的核心需求"