name: Release

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  release:
    name: 构建和发布
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 获取版本号
        id: get_version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Rust Release binary for Linux
        uses: rust-build/rust-build.action@v1.4.5
        with:
          RUSTTARGET: x86_64-unknown-linux-musl
          EXTRA_FILES: README.md
          ARCHIVE_TYPES: tar.gz
          ARCHIVE_NAME: kube-tui-linux-amd64.tar.gz
          TOOLCHAIN_VERSION: stable
          UPLOAD_MODE: none
          STATIC_LINKING: true

      - name: 创建 Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            kube-tui-linux-amd64.tar.gz
          tag_name: ${{ env.VERSION }}
          name: kube-tui ${{ env.VERSION }}
          body: |
            ## What's Changed
            
            * 自动化发布
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}